--------------------------------------------------------
--  File created - pi¹tek-grudzieñ-16-2011   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence KLIENCI_AUTOINC
--------------------------------------------------------

   CREATE SEQUENCE  "BD2A14"."KLIENCI_AUTOINC"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table KLIENCI
--------------------------------------------------------

  CREATE TABLE "BD2A14"."KLIENCI" 
   (	"ID_KLIENTA" NUMBER(32,0), 
	"NUMER_DOKUMENTU" VARCHAR2(32 BYTE), 
	"IMIE" VARCHAR2(32 BYTE), 
	"NAZWISKO" VARCHAR2(64 BYTE), 
	"NUMER_TELEFONU" NUMBER(16,0), 
	"KRAJ" VARCHAR2(32 BYTE), 
	"MIEJSCOWOSC" VARCHAR2(32 BYTE), 
	"KOD_POCZTOWY" VARCHAR2(16 BYTE), 
	"ULICA" VARCHAR2(32 BYTE), 
	"NUMER_ULICY" VARCHAR2(8 BYTE), 
	"NUMER_MIESZKANIA" NUMBER(8,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Table PLATNOSCI
--------------------------------------------------------

  CREATE TABLE "BD2A14"."PLATNOSCI" 
   (	"ID_REZERWACJI" NUMBER(32,0), 
	"ID_TYPU_PLATNOSCI" NUMBER(32,0), 
	"KWOTA" NUMBER(32,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Table POKOJE
--------------------------------------------------------

  CREATE TABLE "BD2A14"."POKOJE" 
   (	"NUMER_POKOJU" NUMBER(32,0), 
	"ID_TYPU_POKOJU" NUMBER(32,0), 
	"NUMER_PIETRA" NUMBER(8,0), 
	"NUMER_TELEFONU" NUMBER(8,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Table POZYCJE_REZERWACJI
--------------------------------------------------------

  CREATE TABLE "BD2A14"."POZYCJE_REZERWACJI" 
   (	"NUMER_POKOJU" NUMBER(32,0), 
	"ID_REZERWACJI" NUMBER(32,0), 
	"OD" DATE, 
	"DO" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Table REZERWACJE
--------------------------------------------------------

  CREATE TABLE "BD2A14"."REZERWACJE" 
   (	"ID_REZERWACJI" NUMBER(32,0), 
	"ID_KLIENTA" NUMBER(32,0), 
	"DATA_ZALOZENIA" DATE, 
	"WARTOSC" NUMBER(32,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Table TYPY_PLATNOSCI
--------------------------------------------------------

  CREATE TABLE "BD2A14"."TYPY_PLATNOSCI" 
   (	"ID_TYPU_PLATNOSCI" NUMBER(32,0), 
	"NAZWA" VARCHAR2(64 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Table TYPY_POKOI
--------------------------------------------------------

  CREATE TABLE "BD2A14"."TYPY_POKOI" 
   (	"ID_TYPU_POKOJU" NUMBER(32,0), 
	"CENA" NUMBER(16,0), 
	"LICZBA_MIEJSC" NUMBER(2,0), 
	"LICZBA_LOZEK" NUMBER(2,0), 
	"OPIS" VARCHAR2(256 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
REM INSERTING into BD2A14.KLIENCI
Insert into BD2A14.KLIENCI (ID_KLIENTA,NUMER_DOKUMENTU,IMIE,NAZWISKO,NUMER_TELEFONU,KRAJ,MIEJSCOWOSC,KOD_POCZTOWY,ULICA,NUMER_ULICY,NUMER_MIESZKANIA) values (1,'dokument2223','mietek33231','iksinsk11i',423232244,null,null,null,null,null,0);
Insert into BD2A14.KLIENCI (ID_KLIENTA,NUMER_DOKUMENTU,IMIE,NAZWISKO,NUMER_TELEFONU,KRAJ,MIEJSCOWOSC,KOD_POCZTOWY,ULICA,NUMER_ULICY,NUMER_MIESZKANIA) values (2,'dokument2223','mietek33231','iksinsk11i',423232244,null,null,null,null,null,0);
REM INSERTING into BD2A14.PLATNOSCI
REM INSERTING into BD2A14.POKOJE
REM INSERTING into BD2A14.POZYCJE_REZERWACJI
REM INSERTING into BD2A14.REZERWACJE
REM INSERTING into BD2A14.TYPY_PLATNOSCI
REM INSERTING into BD2A14.TYPY_POKOI
--------------------------------------------------------
--  DDL for Index PK_TYPY_POKOI
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2A14"."PK_TYPY_POKOI" ON "BD2A14"."TYPY_POKOI" ("ID_TYPU_POKOJU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Index PK_POZYCJE_REZERWACJI
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2A14"."PK_POZYCJE_REZERWACJI" ON "BD2A14"."POZYCJE_REZERWACJI" ("NUMER_POKOJU", "ID_REZERWACJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Index PK_POKOJE
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2A14"."PK_POKOJE" ON "BD2A14"."POKOJE" ("NUMER_POKOJU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Index PK_REZERWACJE
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2A14"."PK_REZERWACJE" ON "BD2A14"."REZERWACJE" ("ID_REZERWACJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Index PK_KLIENCI
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2A14"."PK_KLIENCI" ON "BD2A14"."KLIENCI" ("ID_KLIENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Index PK_TYPY_PLATNOSCI
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2A14"."PK_TYPY_PLATNOSCI" ON "BD2A14"."TYPY_PLATNOSCI" ("ID_TYPU_PLATNOSCI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Index PK_PLATNOSCI
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2A14"."PK_PLATNOSCI" ON "BD2A14"."PLATNOSCI" ("ID_REZERWACJI", "ID_TYPU_PLATNOSCI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  Constraints for Table POKOJE
--------------------------------------------------------

  ALTER TABLE "BD2A14"."POKOJE" ADD CONSTRAINT "PK_POKOJE" PRIMARY KEY ("NUMER_POKOJU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD"  ENABLE;
 
  ALTER TABLE "BD2A14"."POKOJE" MODIFY ("NUMER_POKOJU" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."POKOJE" MODIFY ("ID_TYPU_POKOJU" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."POKOJE" MODIFY ("NUMER_PIETRA" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."POKOJE" MODIFY ("NUMER_TELEFONU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TYPY_PLATNOSCI
--------------------------------------------------------

  ALTER TABLE "BD2A14"."TYPY_PLATNOSCI" ADD CONSTRAINT "PK_TYPY_PLATNOSCI" PRIMARY KEY ("ID_TYPU_PLATNOSCI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD"  ENABLE;
 
  ALTER TABLE "BD2A14"."TYPY_PLATNOSCI" MODIFY ("ID_TYPU_PLATNOSCI" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."TYPY_PLATNOSCI" MODIFY ("NAZWA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KLIENCI
--------------------------------------------------------

  ALTER TABLE "BD2A14"."KLIENCI" ADD CONSTRAINT "PK_KLIENCI" PRIMARY KEY ("ID_KLIENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD"  ENABLE;
 
  ALTER TABLE "BD2A14"."KLIENCI" MODIFY ("ID_KLIENTA" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."KLIENCI" MODIFY ("NUMER_DOKUMENTU" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."KLIENCI" MODIFY ("IMIE" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."KLIENCI" MODIFY ("NAZWISKO" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."KLIENCI" MODIFY ("NUMER_TELEFONU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POZYCJE_REZERWACJI
--------------------------------------------------------

  ALTER TABLE "BD2A14"."POZYCJE_REZERWACJI" ADD CONSTRAINT "PK_POZYCJE_REZERWACJI" PRIMARY KEY ("NUMER_POKOJU", "ID_REZERWACJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD"  ENABLE;
 
  ALTER TABLE "BD2A14"."POZYCJE_REZERWACJI" MODIFY ("NUMER_POKOJU" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."POZYCJE_REZERWACJI" MODIFY ("ID_REZERWACJI" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."POZYCJE_REZERWACJI" MODIFY ("OD" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."POZYCJE_REZERWACJI" MODIFY ("DO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TYPY_POKOI
--------------------------------------------------------

  ALTER TABLE "BD2A14"."TYPY_POKOI" ADD CONSTRAINT "PK_TYPY_POKOI" PRIMARY KEY ("ID_TYPU_POKOJU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD"  ENABLE;
 
  ALTER TABLE "BD2A14"."TYPY_POKOI" MODIFY ("ID_TYPU_POKOJU" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."TYPY_POKOI" MODIFY ("CENA" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."TYPY_POKOI" MODIFY ("LICZBA_MIEJSC" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."TYPY_POKOI" MODIFY ("LICZBA_LOZEK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "BD2A14"."REZERWACJE" ADD CONSTRAINT "PK_REZERWACJE" PRIMARY KEY ("ID_REZERWACJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD"  ENABLE;
 
  ALTER TABLE "BD2A14"."REZERWACJE" MODIFY ("ID_REZERWACJI" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."REZERWACJE" MODIFY ("ID_KLIENTA" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."REZERWACJE" MODIFY ("DATA_ZALOZENIA" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."REZERWACJE" MODIFY ("WARTOSC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLATNOSCI
--------------------------------------------------------

  ALTER TABLE "BD2A14"."PLATNOSCI" ADD CONSTRAINT "PK_PLATNOSCI" PRIMARY KEY ("ID_REZERWACJI", "ID_TYPU_PLATNOSCI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD"  ENABLE;
 
  ALTER TABLE "BD2A14"."PLATNOSCI" MODIFY ("ID_REZERWACJI" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."PLATNOSCI" MODIFY ("ID_TYPU_PLATNOSCI" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."PLATNOSCI" MODIFY ("KWOTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PLATNOSCI
--------------------------------------------------------

  ALTER TABLE "BD2A14"."PLATNOSCI" ADD CONSTRAINT "FK_PLATNOSC_REFERENCE_REZERWAC" FOREIGN KEY ("ID_REZERWACJI")
	  REFERENCES "BD2A14"."REZERWACJE" ("ID_REZERWACJI") ENABLE;
 
  ALTER TABLE "BD2A14"."PLATNOSCI" ADD CONSTRAINT "FK_PLATNOSC_REFERENCE_TYPY_PLA" FOREIGN KEY ("ID_TYPU_PLATNOSCI")
	  REFERENCES "BD2A14"."TYPY_PLATNOSCI" ("ID_TYPU_PLATNOSCI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POKOJE
--------------------------------------------------------

  ALTER TABLE "BD2A14"."POKOJE" ADD CONSTRAINT "FK_POKOJE_REFERENCE_TYPY_POK" FOREIGN KEY ("ID_TYPU_POKOJU")
	  REFERENCES "BD2A14"."TYPY_POKOI" ("ID_TYPU_POKOJU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POZYCJE_REZERWACJI
--------------------------------------------------------

  ALTER TABLE "BD2A14"."POZYCJE_REZERWACJI" ADD CONSTRAINT "FK_POZYCJE__REFERENCE_POKOJE" FOREIGN KEY ("NUMER_POKOJU")
	  REFERENCES "BD2A14"."POKOJE" ("NUMER_POKOJU") ENABLE;
 
  ALTER TABLE "BD2A14"."POZYCJE_REZERWACJI" ADD CONSTRAINT "FK_POZYCJE__REFERENCE_REZERWAC" FOREIGN KEY ("ID_REZERWACJI")
	  REFERENCES "BD2A14"."REZERWACJE" ("ID_REZERWACJI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "BD2A14"."REZERWACJE" ADD CONSTRAINT "FK_REZERWAC_REFERENCE_KLIENCI" FOREIGN KEY ("ID_KLIENTA")
	  REFERENCES "BD2A14"."KLIENCI" ("ID_KLIENTA") ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_KLIENCI_AUTOINC_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BD2A14"."TR_KLIENCI_AUTOINC_ID" before insert on "BD2A14"."KLIENCI"    for each row begin     if inserting then       if :NEW."ID_KLIENTA" is null then          select KLIENCI_AUTOINC.nextval into :NEW."ID_KLIENTA" from dual;       end if;    end if; end;
/
ALTER TRIGGER "BD2A14"."TR_KLIENCI_AUTOINC_ID" ENABLE;
