--------------------------------------------------------
--  File created - wtorek-grudzieñ-20-2011   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence KLIENCI_AUTOINC
--------------------------------------------------------

   CREATE SEQUENCE  "BD2A14"."KLIENCI_AUTOINC"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REZERWACJE_AUTOINC
--------------------------------------------------------

   CREATE SEQUENCE  "BD2A14"."REZERWACJE_AUTOINC"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table KLIENCI
--------------------------------------------------------

  CREATE TABLE "BD2A14"."KLIENCI" 
   (	"ID_KLIENTA" NUMBER(32,0), 
	"NUMER_DOKUMENTU" VARCHAR2(32 BYTE), 
	"IMIE" VARCHAR2(32 BYTE), 
	"NAZWISKO" VARCHAR2(64 BYTE), 
	"NUMER_TELEFONU" NUMBER(16,0), 
	"KRAJ" VARCHAR2(32 BYTE), 
	"MIEJSCOWOSC" VARCHAR2(32 BYTE), 
	"KOD_POCZTOWY" VARCHAR2(16 BYTE), 
	"ULICA" VARCHAR2(32 BYTE), 
	"NUMER_ULICY" VARCHAR2(8 BYTE), 
	"NUMER_MIESZKANIA" NUMBER(8,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Table PLATNOSCI
--------------------------------------------------------

  CREATE TABLE "BD2A14"."PLATNOSCI" 
   (	"ID_REZERWACJI" NUMBER(32,0), 
	"ID_TYPU_PLATNOSCI" NUMBER(32,0), 
	"KWOTA" NUMBER(32,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Table POKOJE
--------------------------------------------------------

  CREATE TABLE "BD2A14"."POKOJE" 
   (	"NUMER_POKOJU" NUMBER(32,0), 
	"ID_TYPU_POKOJU" NUMBER(32,0), 
	"NUMER_PIETRA" NUMBER(8,0), 
	"NUMER_TELEFONU" NUMBER(8,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Table POZYCJE_REZERWACJI
--------------------------------------------------------

  CREATE TABLE "BD2A14"."POZYCJE_REZERWACJI" 
   (	"NUMER_POKOJU" NUMBER(32,0), 
	"ID_REZERWACJI" NUMBER(32,0), 
	"OD" DATE, 
	"DO" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Table REZERWACJE
--------------------------------------------------------

  CREATE TABLE "BD2A14"."REZERWACJE" 
   (	"ID_REZERWACJI" NUMBER(32,0), 
	"ID_KLIENTA" NUMBER(32,0), 
	"DATA_ZALOZENIA" DATE, 
	"WARTOSC" NUMBER(32,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Table TYPY_PLATNOSCI
--------------------------------------------------------

  CREATE TABLE "BD2A14"."TYPY_PLATNOSCI" 
   (	"ID_TYPU_PLATNOSCI" NUMBER(32,0), 
	"NAZWA" VARCHAR2(64 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Table TYPY_POKOI
--------------------------------------------------------

  CREATE TABLE "BD2A14"."TYPY_POKOI" 
   (	"ID_TYPU_POKOJU" NUMBER(32,0), 
	"CENA" NUMBER(16,0), 
	"LICZBA_MIEJSC" NUMBER(2,0), 
	"LICZBA_LOZEK" NUMBER(2,0), 
	"OPIS" VARCHAR2(256 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for View BASIC_CUSTOMERS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "BD2A14"."BASIC_CUSTOMERS" ("NUMER_DOKUMENTU", "IMIE", "NAZWISKO", "NUMER_TELEFONU") AS 
  SELECT NUMER_DOKUMENTU, IMIE, NAZWISKO, NUMER_TELEFONU
    
FROM KLIENCI;
REM INSERTING into BD2A14.KLIENCI
Insert into BD2A14.KLIENCI (ID_KLIENTA,NUMER_DOKUMENTU,IMIE,NAZWISKO,NUMER_TELEFONU,KRAJ,MIEJSCOWOSC,KOD_POCZTOWY,ULICA,NUMER_ULICY,NUMER_MIESZKANIA) values (1,'dokument22','mietek','iksi',5554244,null,null,null,null,null,0);
REM INSERTING into BD2A14.PLATNOSCI
REM INSERTING into BD2A14.POKOJE
Insert into BD2A14.POKOJE (NUMER_POKOJU,ID_TYPU_POKOJU,NUMER_PIETRA,NUMER_TELEFONU) values (1,1,1,1);
Insert into BD2A14.POKOJE (NUMER_POKOJU,ID_TYPU_POKOJU,NUMER_PIETRA,NUMER_TELEFONU) values (2,1,1,2);
Insert into BD2A14.POKOJE (NUMER_POKOJU,ID_TYPU_POKOJU,NUMER_PIETRA,NUMER_TELEFONU) values (3,1,1,3);
REM INSERTING into BD2A14.POZYCJE_REZERWACJI
Insert into BD2A14.POZYCJE_REZERWACJI (NUMER_POKOJU,ID_REZERWACJI,OD,DO) values (1,1,to_date('12/12/12','RR/MM/DD'),to_date('12/12/20','RR/MM/DD'));
Insert into BD2A14.POZYCJE_REZERWACJI (NUMER_POKOJU,ID_REZERWACJI,OD,DO) values (2,2,to_date('12/12/02','RR/MM/DD'),to_date('12/12/11','RR/MM/DD'));
Insert into BD2A14.POZYCJE_REZERWACJI (NUMER_POKOJU,ID_REZERWACJI,OD,DO) values (3,3,to_date('12/12/20','RR/MM/DD'),to_date('12/12/25','RR/MM/DD'));
REM INSERTING into BD2A14.REZERWACJE
Insert into BD2A14.REZERWACJE (ID_REZERWACJI,ID_KLIENTA,DATA_ZALOZENIA,WARTOSC) values (1,1,to_date('12/12/02','RR/MM/DD'),300);
Insert into BD2A14.REZERWACJE (ID_REZERWACJI,ID_KLIENTA,DATA_ZALOZENIA,WARTOSC) values (2,1,to_date('12/12/02','RR/MM/DD'),300);
Insert into BD2A14.REZERWACJE (ID_REZERWACJI,ID_KLIENTA,DATA_ZALOZENIA,WARTOSC) values (3,1,to_date('12/12/02','RR/MM/DD'),300);
REM INSERTING into BD2A14.TYPY_PLATNOSCI
REM INSERTING into BD2A14.TYPY_POKOI
Insert into BD2A14.TYPY_POKOI (ID_TYPU_POKOJU,CENA,LICZBA_MIEJSC,LICZBA_LOZEK,OPIS) values (1,50,2,2,'Opis');
--------------------------------------------------------
--  DDL for Index PK_TYPY_POKOI
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2A14"."PK_TYPY_POKOI" ON "BD2A14"."TYPY_POKOI" ("ID_TYPU_POKOJU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Index PK_POZYCJE_REZERWACJI
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2A14"."PK_POZYCJE_REZERWACJI" ON "BD2A14"."POZYCJE_REZERWACJI" ("NUMER_POKOJU", "ID_REZERWACJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Index PK_POKOJE
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2A14"."PK_POKOJE" ON "BD2A14"."POKOJE" ("NUMER_POKOJU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Index PK_REZERWACJE
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2A14"."PK_REZERWACJE" ON "BD2A14"."REZERWACJE" ("ID_REZERWACJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Index KLIENCI_INDEX1
--------------------------------------------------------

  CREATE INDEX "BD2A14"."KLIENCI_INDEX1" ON "BD2A14"."KLIENCI" ("NUMER_DOKUMENTU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Index PK_KLIENCI
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2A14"."PK_KLIENCI" ON "BD2A14"."KLIENCI" ("ID_KLIENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Index PK_TYPY_PLATNOSCI
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2A14"."PK_TYPY_PLATNOSCI" ON "BD2A14"."TYPY_PLATNOSCI" ("ID_TYPU_PLATNOSCI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  DDL for Index PK_PLATNOSCI
--------------------------------------------------------

  CREATE UNIQUE INDEX "BD2A14"."PK_PLATNOSCI" ON "BD2A14"."PLATNOSCI" ("ID_REZERWACJI", "ID_TYPU_PLATNOSCI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD" ;
--------------------------------------------------------
--  Constraints for Table POKOJE
--------------------------------------------------------

  ALTER TABLE "BD2A14"."POKOJE" ADD CONSTRAINT "PK_POKOJE" PRIMARY KEY ("NUMER_POKOJU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD"  ENABLE;
 
  ALTER TABLE "BD2A14"."POKOJE" MODIFY ("NUMER_POKOJU" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."POKOJE" MODIFY ("ID_TYPU_POKOJU" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."POKOJE" MODIFY ("NUMER_PIETRA" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."POKOJE" MODIFY ("NUMER_TELEFONU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TYPY_PLATNOSCI
--------------------------------------------------------

  ALTER TABLE "BD2A14"."TYPY_PLATNOSCI" ADD CONSTRAINT "PK_TYPY_PLATNOSCI" PRIMARY KEY ("ID_TYPU_PLATNOSCI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD"  ENABLE;
 
  ALTER TABLE "BD2A14"."TYPY_PLATNOSCI" MODIFY ("ID_TYPU_PLATNOSCI" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."TYPY_PLATNOSCI" MODIFY ("NAZWA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KLIENCI
--------------------------------------------------------

  ALTER TABLE "BD2A14"."KLIENCI" ADD CONSTRAINT "PK_KLIENCI" PRIMARY KEY ("ID_KLIENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD"  ENABLE;
 
  ALTER TABLE "BD2A14"."KLIENCI" MODIFY ("ID_KLIENTA" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."KLIENCI" MODIFY ("NUMER_DOKUMENTU" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."KLIENCI" MODIFY ("IMIE" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."KLIENCI" MODIFY ("NAZWISKO" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."KLIENCI" MODIFY ("NUMER_TELEFONU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POZYCJE_REZERWACJI
--------------------------------------------------------

  ALTER TABLE "BD2A14"."POZYCJE_REZERWACJI" ADD CONSTRAINT "PK_POZYCJE_REZERWACJI" PRIMARY KEY ("NUMER_POKOJU", "ID_REZERWACJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD"  ENABLE;
 
  ALTER TABLE "BD2A14"."POZYCJE_REZERWACJI" MODIFY ("NUMER_POKOJU" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."POZYCJE_REZERWACJI" MODIFY ("ID_REZERWACJI" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."POZYCJE_REZERWACJI" MODIFY ("OD" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."POZYCJE_REZERWACJI" MODIFY ("DO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TYPY_POKOI
--------------------------------------------------------

  ALTER TABLE "BD2A14"."TYPY_POKOI" ADD CONSTRAINT "PK_TYPY_POKOI" PRIMARY KEY ("ID_TYPU_POKOJU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD"  ENABLE;
 
  ALTER TABLE "BD2A14"."TYPY_POKOI" MODIFY ("ID_TYPU_POKOJU" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."TYPY_POKOI" MODIFY ("CENA" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."TYPY_POKOI" MODIFY ("LICZBA_MIEJSC" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."TYPY_POKOI" MODIFY ("LICZBA_LOZEK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "BD2A14"."REZERWACJE" ADD CONSTRAINT "PK_REZERWACJE" PRIMARY KEY ("ID_REZERWACJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD"  ENABLE;
 
  ALTER TABLE "BD2A14"."REZERWACJE" MODIFY ("ID_REZERWACJI" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."REZERWACJE" MODIFY ("ID_KLIENTA" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."REZERWACJE" MODIFY ("DATA_ZALOZENIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLATNOSCI
--------------------------------------------------------

  ALTER TABLE "BD2A14"."PLATNOSCI" ADD CONSTRAINT "PK_PLATNOSCI" PRIMARY KEY ("ID_REZERWACJI", "ID_TYPU_PLATNOSCI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BD2_STUD"  ENABLE;
 
  ALTER TABLE "BD2A14"."PLATNOSCI" MODIFY ("ID_REZERWACJI" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."PLATNOSCI" MODIFY ("ID_TYPU_PLATNOSCI" NOT NULL ENABLE);
 
  ALTER TABLE "BD2A14"."PLATNOSCI" MODIFY ("KWOTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PLATNOSCI
--------------------------------------------------------

  ALTER TABLE "BD2A14"."PLATNOSCI" ADD CONSTRAINT "FK_PLATNOSC_REFERENCE_REZERWAC" FOREIGN KEY ("ID_REZERWACJI")
	  REFERENCES "BD2A14"."REZERWACJE" ("ID_REZERWACJI") ENABLE;
 
  ALTER TABLE "BD2A14"."PLATNOSCI" ADD CONSTRAINT "FK_PLATNOSC_REFERENCE_TYPY_PLA" FOREIGN KEY ("ID_TYPU_PLATNOSCI")
	  REFERENCES "BD2A14"."TYPY_PLATNOSCI" ("ID_TYPU_PLATNOSCI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POKOJE
--------------------------------------------------------

  ALTER TABLE "BD2A14"."POKOJE" ADD CONSTRAINT "FK_POKOJE_REFERENCE_TYPY_POK" FOREIGN KEY ("ID_TYPU_POKOJU")
	  REFERENCES "BD2A14"."TYPY_POKOI" ("ID_TYPU_POKOJU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POZYCJE_REZERWACJI
--------------------------------------------------------

  ALTER TABLE "BD2A14"."POZYCJE_REZERWACJI" ADD CONSTRAINT "FK_POZYCJE__REFERENCE_POKOJE" FOREIGN KEY ("NUMER_POKOJU")
	  REFERENCES "BD2A14"."POKOJE" ("NUMER_POKOJU") ENABLE;
 
  ALTER TABLE "BD2A14"."POZYCJE_REZERWACJI" ADD CONSTRAINT "FK_POZYCJE__REFERENCE_REZERWAC" FOREIGN KEY ("ID_REZERWACJI")
	  REFERENCES "BD2A14"."REZERWACJE" ("ID_REZERWACJI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "BD2A14"."REZERWACJE" ADD CONSTRAINT "FK_REZERWAC_REFERENCE_KLIENCI" FOREIGN KEY ("ID_KLIENTA")
	  REFERENCES "BD2A14"."KLIENCI" ("ID_KLIENTA") ENABLE;
--------------------------------------------------------
--  DDL for Trigger BASIC_CUSTOMER_INSERT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BD2A14"."BASIC_CUSTOMER_INSERT" INSTEAD OF INSERT ON BASIC_CUSTOMERS 
REFERENCING NEW AS new 
FOR EACH ROW 
DECLARE
	rowcnt number;
BEGIN
  SELECT COUNT(*) INTO rowcnt FROM KLIENCI WHERE NUMER_DOKUMENTU = :new.NUMER_DOKUMENTU;
  IF rowcnt = 0 THEN
	INSERT INTO KLIENCI VALUES(NULL, :new.NUMER_DOKUMENTU, :new.IMIE, :new.NAZWISKO, :new.NUMER_TELEFONU, NULL, NULL, NULL, NULL, NULL, NULL);
  ELSE
	SELECT COUNT(*) INTO rowcnt FROM KLIENCI WHERE NUMER_DOKUMENTU = :new.NUMER_DOKUMENTU and IMIE = :new.IMIE and NAZWISKO = :new.NAZWISKO;
		IF rowcnt = 0 THEN
		 raise_application_error (-20999,'Customer credentials does not match. Document might be stolen.');
		ELSE
			UPDATE KLIENCI SET NUMER_TELEFONU = :new.NUMER_TELEFONU
			WHERE NUMER_DOKUMENTU = :new.NUMER_DOKUMENTU;
		END IF;
  END IF;
  
END;
/
ALTER TRIGGER "BD2A14"."BASIC_CUSTOMER_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REZERWACJE_TRIGGER_AUTOINC
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BD2A14"."REZERWACJE_TRIGGER_AUTOINC" before insert on "BD2A14"."REZERWACJE"    for each row begin     if inserting then       if :NEW."ID_REZERWACJI" is null then          select REZERWACJE_AUTOINC.nextval into :NEW."ID_REZERWACJI" from dual;       end if;    end if; end;
/
ALTER TRIGGER "BD2A14"."REZERWACJE_TRIGGER_AUTOINC" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_KLIENCI_AUTOINC_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BD2A14"."TR_KLIENCI_AUTOINC_ID" before insert on "BD2A14"."KLIENCI"    for each row begin     if inserting then       if :NEW."ID_KLIENTA" is null then          select KLIENCI_AUTOINC.nextval into :NEW."ID_KLIENTA" from dual;       end if;    end if; end;
/
ALTER TRIGGER "BD2A14"."TR_KLIENCI_AUTOINC_ID" ENABLE;
