package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;

import javax.sql.RowSet;

/*
 * int 1	id
string 2	documentID
string 3	name
string 4	lastName
int    5	phoneNumber
string 6	country
string 7	city
string 8	postCode
string 9	street
string 10	streetNumber
int	   11	flatNumber
 */


public class OracleCustomerDAO implements CustomerDAO {

	@Override
	public int insertCustomer(Customer customer) {
		Connection connection = OracleDAOFactory.createConnection();
		
		PreparedStatement addCustomer = null;
		PreparedStatement selectID = null;
		
		String addCustomerStmt = "INSERT INTO KLIENCI VALUES (null,?,?,?,?,?,?,?,?,?,?)";
		String selectIDQuery = "SELECT MAX(ID_KLIENTA) FROM KLIENCI";
		int id = -1;
		try {
			addCustomer = connection.prepareStatement(addCustomerStmt);
			//addCustomer.setInt(1, customer.getId());
			addCustomer.setString(1, customer.getDocumentID());
			addCustomer.setString(2, customer.getName());
			addCustomer.setString(3, customer.getLastName());
			addCustomer.setInt(4, customer.getPhoneNumber());
			addCustomer.setString(5, customer.getCountry());
			addCustomer.setString(6, customer.getCity());
			addCustomer.setString(7, customer.getPostCode());
			addCustomer.setString(8, customer.getStreet());
			addCustomer.setString(9, customer.getStreetNumber());
			addCustomer.setInt(10, customer.getFlatNumber());
			
			addCustomer.execute();
			
			// TODO I guess there should be another select query to obtain
			// ID of the inserted customer because that ID will be probably
			// generated by a trigger
			
			// implementing this now..
			selectID = connection.prepareStatement(selectIDQuery);
			ResultSet res = selectID.executeQuery();
			while(res.next()){
				id = res.getInt(1);
			}
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return id;
	}

	@Override
	public boolean deleteCustomer(Customer customer) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public Customer findCustomer(int id) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean updateCustomer(Customer customer) {
		// TODO Auto-generated method stub
		return false;
	}

	// not sure if this method is usefull
	@Override
	public ResultSet selectCustomersRS() {
		
		return null;
	}

	@Override
	public List<Customer> selectCustomersTO() {
		Connection connection = OracleDAOFactory.createConnection();
		List<Customer> list = new LinkedList<Customer>();
		PreparedStatement selectAllCustomers = null;
		
		String selectAllCustomersStmt = "SELECT * FROM KLIENCI";
		
		try{
			selectAllCustomers = connection.prepareStatement(selectAllCustomersStmt);
			ResultSet res = selectAllCustomers.executeQuery();
			
			while(res.next()){
				Customer c = new Customer();

				c.setId(res.getInt(1));
				c.setDocumentID(res.getString(2));
				c.setName(res.getString(3));
				c.setLastName(res.getString(4));
				c.setPhoneNumber(res.getInt(5));
				c.setCountry(res.getString(6));
				c.setCity(res.getString(7));
				c.setPostCode(res.getString(8));
				c.setStreet(res.getString(9));
				c.setStreetNumber(res.getString(10));
				c.setFlatNumber(res.getInt(11));

				list.add(c);
			}
			
		} catch (SQLException e){
			e.printStackTrace();
		}
		
		return list;
	}

}
